### ISSUE TITLE
Error in Global Error Trapper

### ISSUE THREAD

**Issue by marirene12** [thkruz/keeptrack.space#790] opened 2023-10-30 10:37 UTC
#### User Description
Type what you were trying to do here...

#### Error Title
Error
#### Error Message
Vertex shader compilation failed: 
#### Stack
Error: Vertex shader compilation failed: 
    at i.createVertexShader (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:708:97363)
    at i.createProgramFromCode (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:708:93502)
    at Se.initGodraysProgram_ (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:1340:2420)
    at Se.initGodrays (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:1340:1750)
    at Ae.resizePostProcessingTexture (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:1340:18024)
    at Ae.drawOptionalScenery (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:1340:9450)
    at Ae.draw (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:1340:9083)
    at Ye.draw_ (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:1444:2984)
    at Ye.gameLoop (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:1391:15812)

**Comment by thkruz** [comment] 2023-11-01 23:33
Closing as duplicate of #789

**Closed by thkruz** 2023-11-01 23:33 UTC
Labels: Duplicate
