### ISSUE TITLE
Error in Global Error Trapper: Satellite position is undefined

### ISSUE THREAD

**Issue by xli2522** [thkruz/keeptrack.space#793] opened 2023-11-06 23:26 UTC
#### User Description
- Error first occurred when embedding sat view [57317](https://www.keeptrack.space/app/?sat=57317) to a Notion page. 
- Was able to reproduce this error consistently with Chrome Version 119.0.6045.106 (Official Build) (64-bit) in **incognito mode**. 
- No error in regular browsing mode.

#### Error Title
Error
#### Error Message
Satellite position is undefined
#### Stack
Error: Satellite position is undefined
    at A.snapToSat (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:708:21391)
    at Ae.satCalculate (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:1340:18510)
    at Ae.updateLoop (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:1340:20008)
    at Ye.update_ (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:1444:6690)
    at Ye.gameLoop (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:1391:15796)

**Comment by thkruz** [comment] 2023-11-08 03:16
Are you able to post or email me (theodore.kruczek@gmail.com) the notion page? I am running keeptrack.space/app in Version 119.0.6045.106 (Official Build) (64-bit) in incognito mode without any errors. 

Does it do it when you run incognito without doing sat view? 

It could be a race condition - things I would look for is checking to see if all three threads are running, in particular positionCruncher.js. I don't know if notion or Incognito is blocking the web workers from running and then you won't have position/velocity or orbits (totally unusable).

Very happy to take a look for you, but I'd need to see what the environment looks on your end.

**Comment by thkruz** [comment] 2023-11-08 03:18
Might be related to #775. I will look into doing more validation before trying to launch the app if there is a delay in something loading in the webworker.

**Comment by thkruz** [comment] 2023-11-08 03:28
Got it! Race condition caused by an async call to get position and velocity data before the first time velocity is calculated.

At t=0 there is position but undefined velocity. At t=1 there is both. In almost all cases the call to get positionAndVelocity takes at least one full game loop to execute and there is no problem. My guess is that in incognito mode your cache is getting cleared and the images downloading is changing the timing of everything.

Thank you so much for more context - I should be able to get this and #775 fixed tonight and pushed in the next day or so.

**Comment by thkruz** [comment] 2023-11-08 04:53
Fixed in #788

**Closed by thkruz** 2023-11-08 04:53 UTC
Labels: Bug

**Comment by xli2522** [comment] 2023-11-08 15:14
> Does it do it when you run incognito without doing sat view?

It only occurs when a satellite is selected in the app.


> My guess is that in incognito mode your cache is getting cleared and the images downloading is changing the timing of everything.

I agree, the error is probably caused by a component not being ready when loaded for the first time. Loading the sat view multiple times in one incognito session resolves the error.


> I don't know if notion or Incognito is blocking the web workers from running and then you won't have position/velocity or orbits (totally unusable).

I did not experience any other issues.

Thanks for taking a look and fixing it! I will let you know if it happens again.

**Comment by xli2522** [comment] 2023-11-08 22:08
No error with the dev gh-page! Thanks!
