### ISSUE TITLE
Error while building generic type   [tsl] ERROR in D:\master\software\keeptrack.space-develop\src\js\interfaces.ts(21,23)         TS2315: Type 'Vec3Flat' is not generic.

### ISSUE THREAD

**Issue by Ahmed-Refaat** [thkruz/keeptrack.space#698] opened 2023-08-25 09:18 UTC
#### Steps to reproduce 
1.   [tsl] ERROR in D:\master\software\keeptrack.space-develop\src\js\interfaces.ts(21,23)
        TS2315: Type 'Vec3Flat' is not generic.
2. Write here

#### Current behaviour (bug)
  [tsl] ERROR in D:\master\software\keeptrack.space-develop\src\js\interfaces.ts(21,23)
        TS2315: Type 'Vec3Flat' is not generic.

#### Expected behaviour (correct)
Write here

#### Relevant logs and/or media (optional)
```
Write here or upload an image/video
```

#### Other comment (optional)
Write here

#### Reported by
Write here

**Comment by thkruz** [comment] 2023-11-01 23:36
This was caused by a mismatch in the ootk version online and the version I was using internally. It should be fixed now if you install the latest version of ootk (just do another npm i on keeptrack).

**Closed by thkruz** 2023-11-01 23:36 UTC
